AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  LambdaEC2statechangeSAM:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Calc.lambda_handler
      Runtime: python3.9
      Role: arn:aws:iam::960966738908:role/CloudwatchRoleforLambda
      Timeout: 120
      CodeUri: s3://rajani-martha/011d063087ff4c5f2c1000467cebf41e
    Metadata:
      SamResourceId: LambdaEC2statechangeSAM
